DROP TABLE COMMENT;
CREATE TABLE COMMENT(
    CommentId INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(30),
    PostId INT,
    CommentText VARCHAR(250) NOT NULL,
    CommentTime DATETIME,
    FOREIGN KEY (Username) REFERENCES USER(Username),
    FOREIGN KEY (PostId) REFERENCES BLOG_POST(PostId)
);